[package]
name = "parse-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = "0.37.1"
log = "0.4.22"
serde = { version = "1.0.217", features = ["derive"] }

[dev-dependencies]
env_logger = "0.11.6"
